### ISSUE TITLE
Catch exception when calling nmap

### ISSUE THREAD

**Issue by temparus** [temparus/network-monitoring.py#1]
We should catch exceptions which could be thrown by the nmap call.

Example:
```
Segmentation fault (core dumped)
Traceback (most recent call last):
  File "./network-monitoring.py", line 77, in <module>
    result = host_scan(hosts)
  File "/home/amivadmin/network-monitoring/host_scan.py", line 19, in host_scan
    output = subprocess.check_output('nmap --script vuln ' + host.get('hostname', host.get('ip', '')), shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'nmap --script vuln <hostname>' returned non-zero exit status 139
```

**Comment by temparus** [comment]
Fixed with commit cdd5e3c8d1c0fbd60efb785223ba074ceed3102f
